<?php namespace Jehaby\Kindle;


use Illuminate\Support\Collection;


class HighlightsCollection extends Collection {


    public function groupByBooks()
    {
        return (new Collection($this->items))->groupBy(function($highlight) {
            return $highlight->getBook();
        });
    }

    /**
     * Push an item onto the end of the collection.
     *
     * @param  mixed $value
     * @return $this
     */
    public function push($value)
    {
        if ($value instanceof Highlight) {
            return parent::push($value); // TODO: Change the autogenerated stub
        }

        throw new \InvalidArgumentException('Should be instance of Highlight');
    }


    /*
      

     */
    public function getPhrases()
    {
        return $this->filter(function (Highlight $item) {
            return $item->getType() === Highlight::PHRASE;
        });
    }


    public function getWords()
    {
        return $this->filter(function (Highlight $item) {
            return $item->getType() === Highlight::WORD;
        });
    }


    public function getCollocations()
    {

    }


    public function getByType()
    {

    }

    
    public function getEnglish()
    {

    }

    
    public function getRussian()
    {

    }

    
    public function getFromBook($book)
    {
        return $this->filter(function($item) use ($book) {
            return trim($item->getBook()) == $book;
        }) ;
    }

    
    

}


